# Generated by Django 4.1.5 on 2023-01-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parent', models.IntegerField(null=True)),
                ('menuName', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuElement',
        ),
    ]
